# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chewing Gum and Paperclips: an IT story
email: azurenus16@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tips, Tricks, and Fixes that I come across as I further fall
  into madness. Sometimes, I throw in opinions about video games
  or IT things in here too. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: azurenus
github_username:  azurenus

# Build settings
markdown: kramdown
